
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">

            <a class="navbar-brand" href="<?php echo $this->url('home');?>">
                <img class="header-logo" src="<?php echo $this->basePath('img/header-logo.png') ?>" alt="Uprinting"/>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right header-links">
                <?php
                if(!isset($this->layout()->first_name)){ ?>
                <a class="header-links" href="<?php echo $this->url('customer');?>">Login</a>
                <?php } else{ echo $this->layout()->first_name; ?> || <a class="header-links" href="<?php echo $this->url('customer', array('action' => 'logout'));?>">Logout</a><?php }?> ||
                <a class= "header-links" href="<?php echo $this->url('cart');?>">Cart</a>
            </ul>
        </div>
    </div>
</nav>
