<!--/**
 * Created by PhpStorm.
 * User: ignacio.i
 * Date: 4/28/2016
 * Time: 6:24 PM
 */-->
<html lang="en">
    <head>
		<?php echo $this->render('APP_CSS_SCRIPTS') ?>
</head>

<body>
<div class="container">
<?php echo $this->render('APP_HEADER') ?>
<br><br>
<div class="page-contents">
    <?php echo $this->content; ?>
</div>
</div>

<?php echo $this->render('APP_JAVA_SCRIPTS') ?>
</body>
</html>
